### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by MDSADABWASIM** [avirias/Grey#1]
hello, I just cloned your repo and want to run it but it gives me exceptions seems like you changed a lot of things in flute_plugin  song class, if you can share that code too, it'll be very helpful.

**Comment by avirias** [comment]
`###` here's the updated class

```
class Song {
  int id;
  String artist;
  String title;
  String album;
  int albumId;
  int duration;
  String uri;
  String albumArt;
  int isFav=0;
  int timestamp=0;
  int count=0;

  Song(this.id, this.artist, this.title, this.album, this.albumId,
      this.duration, this.uri, this.albumArt,{this.isFav=0,this.timestamp=0,this.count=0});

  Song.fromMap(Map m) {
    id = m["id"];
    artist = m["artist"];
    title = m["title"];
    album = m["album"];
    albumId = m["albumId"];
    duration = m["duration"];
    uri = m["uri"];
    albumArt = m["albumArt"];
    isFav=m["isFav"];
    timestamp=m["timestamp"];
    count=m["count"];
  }
  static final Columns=["id","artist", "title", "album", "albumId", "duration", "uri", "albumArt","isFav","timestamp"];

  Map toMap(){
    Map<String,dynamic> map={
      "id":id,
      "artist":artist,
      "title":title,
      "album":album,
      "albumId":albumId,
      "duration":duration,
      "uri":uri,
      "albumArt":albumArt,
      "isFav":isFav,
      "timestamp":timestamp,
      "count":count,
    };
    return map;
  }
}
```

**Comment by MDSADABWASIM** [comment]
Thanks for your response, @avirias 
Now when I run it shows me this error
![error2](https://user-images.githubusercontent.com/30585197/43116906-ab3b5618-8f27-11e8-9f2b-4d2171766d33.png)
caused by this method 
**getSharedData() async {
    const platform = const MethodChannel('app.channel.shared.data');
    Map sharedData = await platform.invokeMethod("getSharedData");
    if (sharedData != null) {
      if (sharedData["albumArt"] == "null") {
        sharedData["albumArt"] = null;
      }
      Song song = new Song(
          9999 /*random*/,
          sharedData["artist"],
          sharedData["title"],
          sharedData["album"],
          null,
          int.parse(sharedData["duration"]),
          sharedData["uri"],
          sharedData["albumArt"]);
      List<Song> list = new List();
      list.add((song));
      MyQueue.songs = list;
      Navigator.of(context).push(new MaterialPageRoute(builder: (context) {
        return new NowPlaying(null, list, 0, 0);
      }));
    }
  }** in musicHome class
when I step out the error it runs again and then throws this error
![error3](https://user-images.githubusercontent.com/30585197/43116924-c83059da-8f27-11e8-8df6-e81160f19839.png)
caused by this method

  **Future<Song> fetchLastSong() async {
    List<Map> results = await _db
        .rawQuery("select * from songs order by timestamp desc limit 1");
    Song song;
    results.forEach((s) {
      song = new Song.fromMap(s);
    });
    print("Last" +  song.title);
    return song;
  }**
in database class.
