### ISSUE TITLE
a lot of errors and bugs 

### ISSUE THREAD

**Issue by badr131** [avirias/Grey#10]
Hi 

Seems like this project is not working at all , it has a lot of errors inside 
could you check that please . 

![image](https://user-images.githubusercontent.com/52708808/62352404-bad2eb80-b510-11e9-918b-dda7edee075f.png)

**Comment by avirias** [comment]
you have to update the plugin's song class
https://github.com/avirias/Grey/issues/1#issuecomment-407253918
