### ISSUE TITLE
Cant play songs

### ISSUE THREAD

**Issue by taimuralam** [avirias/Grey#15]
![Screenshot_20191114-150722](https://user-images.githubusercontent.com/26968659/68844912-8d413500-06f0-11ea-9298-46b834edecfc.jpg)
As soon as I play any music it throws this error.

**Comment by avirias** [comment]
solved it in this [commit](https://github.com/avirias/Grey/commit/16ee10bc5e378dba57335c6bb1e2016988c6a572).
