### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by alankley** [avirias/Grey#17]
As of today, latest code does not compile.
Appears to be referencing missing fields in Song from flute_music_player library (0.0.6) 

error: The getter 'Columns' isn't defined for the class 'Song'. (undefined_getter at [musicplayer] lib/database/database_client.dart:38)
error: The setter 'count' isn't defined for the class 'Song'. (undefined_setter at [musicplayer] lib/database/database_client.dart:53)
error: The getter 'timestamp' isn't defined for the class 'Song'. (undefined_getter at [musicplayer] lib/database/database_client.dart:55)
error: The getter 'isFav' isn't defined for the class 'Song'. (undefined_getter at [musicplayer] lib/database/database_client.dart:58)

**Comment by avirias** [comment]
#1
