### ISSUE TITLE
Problem With Database 

### ISSUE THREAD

**Issue by Kawshik-khan** [avirias/Grey#20]
{
	"resource": "/H:/Flutter Workshop/Github Project/Grey/lib/database/database_client.dart",
	"owner": "dart",
	"code": {
		"value": "undefined_getter",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#undefined_getter",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "undefined_getter"
		}
	},
	"severity": 8,
	"message": "The getter 'Columns' isn't defined for the type 'Song'.\nTry importing the library that defines 'Columns', correcting the name to the name of an existing getter, or defining a getter or field named 'Columns'.",
	"source": "dart",
	"startLineNumber": 38,
	"startColumn": 67,
	"endLineNumber": 38,
	"endColumn": 74,
	"tags": []
}

**Comment by avirias** [comment]
Updated class is available [here](https://github.com/avirias/Grey/issues/1#issuecomment-407253918)
