### ISSUE TITLE
Cannot log in to Google account

### ISSUE THREAD

**Issue by Kalela** [avirias/Grey#21]
When attempting to log in to my Google account to get my data from Google. I get this prompt. Then get stuck in the sign in with google page unless I close the app. I'm running android 11.
![Screenshot_20200929-181456](https://user-images.githubusercontent.com/33759757/94578584-98597100-0280-11eb-840a-9e06e937900c.png)

**Comment by avirias** [comment]
I don't think this issue relates to the app.

**Comment by Kalela** [comment]
Does the app launch my current browser for google authentication? Or does it use a web view embedded into the application?

**Comment by Kalela** [comment]
Wrong repo...smh. Apologies for this.
