### ISSUE TITLE
Sync between my devices

### ISSUE THREAD

**Issue by ghost** [avirias/Grey#4]
Would be great is there was a way for my recent data table to be synchronised across all my devices.

Maybe some open simple data storage solution. In order to not have a clash on sync all mutations need to go to a queue.
The onboard storage needs to be indempotent so an insert for an already existing row does not fail. This will happen when the mutation ripples to the device it came from.

You could maybe make the db P2P with no cloud by use webrtc. All devices need a global key so each knows all the others 

Anyway just brainstorming ideas.

**Comment by avirias** [comment]
Thanks, I'll try to implement this idea
