### ISSUE TITLE
length was called on null

### ISSUE THREAD

**Issue by OmarHatem28** [avirias/Grey#6]
When playing most of the songs, it gives me this exception.

![54524246_274313236801992_1105912340227817472_n](https://user-images.githubusercontent.com/31170694/54672703-669b1200-4b01-11e9-98e2-b43e0446be9b.jpg)

When I tried developing a music player app with flutter, I had the same issue but removed it by casting the songs var ( which is returned from await MusicFinder.allSongs(); ) to Song class.

I wanted to suggest that you do the same, but then I tried to remove the casting and stick to ( new List.from(songs); ) as before, and it didn't give me this exception anymore, don't know why.

so now I don't actually know what is causing the exception, but you can try my solution and tell me the results, and your conclusions.

**Comment by Aakash-DD** [comment]
Do u get any solution for this??

**Comment by avirias** [comment]
#15
